name: "Label Syncer"
description: "Sync GitHub labels in the declarative way."
author: "micnncim"
inputs:
  manifest:
    description: "File path of YAML manifest for labels"
    required: false
    default: ".github/labels.yml"
  repository:
    description: "The repo to sync labels on (defaults to current repo)"
    required: false
  token:
    description: "An alternative GitHub token to use instead"
    required: false
  prune:
    description: "Remove unmanaged labels from repository"
    required: false
    default: true
  labelExcludePattern:
    description: "Regular expression to exclude labels from syncing"
    required: false
  dryRun:
    description: "No label is create/updated or deleted"
    required: false
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: circle
  color: black
